import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "Cypher",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
